<?php
//ACF Google Maps API 
function theme_acf_google_map_api( $api ){
	$api['key'] = 'API_KEY';
	return $api;
}
add_filter('acf/fields/google_map/api', 'theme_acf_google_map_api');


//ACF Fields
if( function_exists('acf_add_local_field_group') ):
acf_add_local_field_group(array(
	'key' => 'group_599ddd9c4a2e9',
	'title' => 'Event Information',
	'fields' => array(
		array(
			'key' => 'field_5581b111e91c5',
			'label' => 'Event Description',
			'name' => 'event_description',
			'type' => 'textarea',
			'instructions' => 'Max. Length: 224 Characters',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 224,
			'rows' => '',
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_5584aec8c5e55',
			'label' => 'Event Days',
			'name' => 'event_days',
			'type' => 'text',
			'instructions' => 'Format: mm/dd/yyyy. Separate multiple dates with a comma then a space. Example: 02/03/1989, 02/23/1992, 09/29/2017.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_59b06f1ec0b70',
			'label' => 'Event Date Info',
			'name' => 'event_date_info',
			'type' => 'text',
			'instructions' => 'Special way to list event\'s time. ie- "Every Thursday at 8PM between 12/4 and 12/18."',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5581b042e91c3',
			'label' => 'Admission Charged',
			'name' => 'admission_charged',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5584b2d039b1c',
			'label' => 'Admission Fee',
			'name' => 'event_fee',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5581b042e91c3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5584b1f8fda69',
			'label' => 'Event Website',
			'name' => 'event_website',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5581b3745f09f',
			'label' => 'Venue Phone Number',
			'name' => 'event_phone',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5581af9fe91c1',
			'label' => 'Venue Address',
			'name' => 'event_address',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5584b123df949',
			'label' => 'Venue Address Line 2',
			'name' => 'event_address2',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5584b194b129d',
			'label' => 'Venue City',
			'name' => 'event_city',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5584b1b44ef45',
			'label' => 'Venue State',
			'name' => 'event_state',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5584b1cc52202',
			'label' => 'Venue Zip / Postal Code',
			'name' => 'event_zip',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'event',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'excerpt',
		1 => 'custom_fields',
		2 => 'discussion',
		3 => 'comments',
		4 => 'author',
		5 => 'format',
		6 => 'categories',
		7 => 'tags',
		8 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_59aef6cdc15f1',
	'title' => 'Post Media',
	'fields' => array(
		array(
			'key' => 'field_59af11b22b8f0',
			'label' => 'Media',
			'name' => 'media',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '+ Add Media Item',
			'sub_fields' => array(
				array(
					'key' => 'field_59af11e62b8f2',
					'label' => 'Media Type',
					'name' => 'media_type',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Image' => 'Image',
						'YouTube Video' => 'YouTube Video',
						'PDF' => 'PDF',
						'Link' => 'Link',
					),
					'default_value' => array(
					),
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_59af11bf2b8f1',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59af11e62b8f2',
								'operator' => '!=',
								'value' => '',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_59af12042b8f3',
					'label' => 'Image Focal Point',
					'name' => 'image_focal_point',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59af11e62b8f2',
								'operator' => '!=',
								'value' => '',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Center' => 'Center',
						'Left Center' => 'Left Center',
						'Right Center' => 'Right Center',
						'Center Top' => 'Center Top',
						'Left Top' => 'Left Top',
						'Right Top' => 'Right Top',
						'Center Bottom' => 'Center Bottom',
						'Left Bottom' => 'Left Bottom',
						'Right Bottom' => 'Right Bottom',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_59af121d2b8f4',
					'label' => 'Link URL',
					'name' => 'link_url',
					'type' => 'url',
					'instructions' => 'Enter link to PDF, YouTube Video, or any site. Defaults to the image URL.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59af11e62b8f2',
								'operator' => '!=',
								'value' => '',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_59af122b2b8f5',
					'label' => 'Caption',
					'name' => 'caption',
					'type' => 'text',
					'instructions' => '150 Character Limit',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59af11e62b8f2',
								'operator' => '!=',
								'value' => '',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 150,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'event',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_59a2f5fadcdec',
	'title' => 'Segments',
	'fields' => array(
		array(
			'key' => 'field_59a2f5fae361a',
			'label' => 'Segments',
			'name' => 'segments',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '+ Add Segment',
			'sub_fields' => array(
				array(
					'key' => 'field_59a2f5fae61b3',
					'label' => 'Segment Type',
					'name' => 'segment_type',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Text' => 'Text',
						'Text and Media' => 'Text and Media',
						'Only Media' => 'Only Media',
						'Text and Content Group' => 'Text and Content Group',
						'Content Group Only' => 'Content Group Only',
						'Callout' => 'Callout',
						'Info Box' => 'Info Box',
						'Contact Info' => 'Contact Info',
					),
					'default_value' => array(
					),
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_59a2f5fae61ca',
					'label' => 'Text',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Callout',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Info Box',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Content Group',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_59a2f5fae6204',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Callout',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Info Box',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Content Group',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_59ebe6e3787eb',
					'label' => 'Subtitle',
					'name' => 'subtitle',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Callout',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Info Box',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Content Group',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_59a2f5fae6251',
					'label' => 'Body',
					'name' => 'body',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Callout',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Info Box',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Content Group',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 0,
				),
				array(
					'key' => 'field_59a2f5fae628a',
					'label' => 'Media',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Only Media',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_59a2f5fae62b5',
					'label' => 'Add Media',
					'name' => 'add_media',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Only Media',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Single Media Item' => 'Single Media Item',
						'Portrait and Landscape' => 'Portrait and Landscape',
						'Grid' => 'Grid',
						'Slideshow' => 'Slideshow',
					),
					'default_value' => array(
					),
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_59a2f5fae6315',
					'label' => 'Media',
					'name' => 'media',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae62b5',
								'operator' => '==',
								'value' => 'Slideshow',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Only Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae62b5',
								'operator' => '==',
								'value' => 'Slideshow',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae62b5',
								'operator' => '==',
								'value' => 'Grid',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Only Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae62b5',
								'operator' => '==',
								'value' => 'Grid',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '+ Add Media',
					'sub_fields' => array(
						array(
							'key' => 'field_59a2f5fb050f2',
							'label' => 'Media Type',
							'name' => 'media_type',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Image' => 'Image',
								'YouTube Video' => 'YouTube Video',
								'PDF' => 'PDF',
								'Link' => 'Link',
							),
							'default_value' => array(
							),
							'allow_null' => 1,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_59a2f5fb05107',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_59a2f5fb050f2',
										'operator' => '!=',
										'value' => '',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_59aed42421c07',
							'label' => 'Image Focal Point',
							'name' => 'image_focal_point',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_59a2f5fb050f2',
										'operator' => '!=',
										'value' => '',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Center' => 'Center',
								'Left Center' => 'Left Center',
								'Right Center' => 'Right Center',
								'Center Top' => 'Center Top',
								'Left Top' => 'Left Top',
								'Right Top' => 'Right Top',
								'Center Bottom' => 'Center Bottom',
								'Left Bottom' => 'Left Bottom',
								'Right Bottom' => 'Right Bottom',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_59a2f5fb05117',
							'label' => 'Link URL',
							'name' => 'link_url',
							'type' => 'url',
							'instructions' => 'Enter link to PDF, YouTube Video, or any site. Defaults to the image URL.',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_59a2f5fb050f2',
										'operator' => '!=',
										'value' => '',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_59a2f5fb05128',
							'label' => 'Caption',
							'name' => 'caption',
							'type' => 'text',
							'instructions' => '150 Character Limit',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_59a2f5fb050f2',
										'operator' => '!=',
										'value' => '',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => 150,
						),
					),
				),
				array(
					'key' => 'field_59a2f5fae6340',
					'label' => 'Single Media Item',
					'name' => 'single_media_item',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae62b5',
								'operator' => '==',
								'value' => 'Single Media Item',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae62b5',
								'operator' => '==',
								'value' => 'Single Media Item',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Only Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae62b5',
								'operator' => '==',
								'value' => 'Portrait and Landscape',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae62b5',
								'operator' => '==',
								'value' => 'Portrait and Landscape',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Only Media',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'sub_fields' => array(
						array(
							'key' => 'field_599f2de62617e',
							'label' => 'Media Type',
							'name' => 'media_type',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_59a2f5fae62b5',
										'operator' => '==',
										'value' => 'Single Media Item',
									),
								),
								array(
									array(
										'field' => 'field_59a2f5fae62b5',
										'operator' => '==',
										'value' => 'Portrait and Landscape',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Image' => 'Image',
								'YouTube Video' => 'YouTube Video',
								'PDF' => 'PDF',
								'Link' => 'Link',
							),
							'default_value' => array(
							),
							'allow_null' => 1,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_599f2de62617f',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_599f2de62617e',
										'operator' => '!=',
										'value' => '',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_59aed3f521c05',
							'label' => 'Sizing Preset',
							'name' => 'sizing_preset',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_599f2de62617e',
										'operator' => '!=',
										'value' => '',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Landscape' => 'Landscape',
								'Portrait' => 'Portrait',
								'Square' => 'Square',
							),
							'default_value' => array(
							),
							'allow_null' => 1,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_59aed3f521c06',
							'label' => 'Image Focal Point',
							'name' => 'image_focal_point',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_599f2de62617e',
										'operator' => '!=',
										'value' => '',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Center' => 'Center',
								'Left Center' => 'Left Center',
								'Right Center' => 'Right Center',
								'Center Top' => 'Center Top',
								'Left Top' => 'Left Top',
								'Right Top' => 'Right Top',
								'Center Bottom' => 'Center Bottom',
								'Left Bottom' => 'Left Bottom',
								'Right Bottom' => 'Right Bottom',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_599f2de626183',
							'label' => 'Caption',
							'name' => 'caption',
							'type' => 'text',
							'instructions' => '150 Character Limit',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_599f2de62617e',
										'operator' => '!=',
										'value' => '',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => 150,
						),
						array(
							'key' => 'field_599f2de626182',
							'label' => 'Link URL',
							'name' => 'link_url',
							'type' => 'url',
							'instructions' => 'Enter link to PDF, YouTube Video, or any site. Defaults to the image URL.',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_599f2de62617e',
										'operator' => '!=',
										'value' => '',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
				),
				array(
					'key' => 'field_59a2f5fae635f',
					'label' => 'Portrait Media Item',
					'name' => 'portrait_media_item',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae62b5',
								'operator' => '==',
								'value' => 'Portrait and Landscape',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae62b5',
								'operator' => '==',
								'value' => 'Portrait and Landscape',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Only Media',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'sub_fields' => array(
						array(
							'key' => 'field_599f2f1a26188',
							'label' => 'Media Type',
							'name' => 'media_type',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_59a2f5fae62b5',
										'operator' => '==',
										'value' => 'Portrait and Landscape',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Image' => 'Image',
								'YouTube Video' => 'YouTube Video',
								'PDF' => 'PDF',
								'Link' => 'Link',
							),
							'default_value' => array(
							),
							'allow_null' => 1,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_599f2f1a26189',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_599f2f1a26188',
										'operator' => '!=',
										'value' => '',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_59aed3ca21c05',
							'label' => 'Image Focal Point',
							'name' => 'image_focal_point',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_59a2f5fae61b3',
										'operator' => '!=',
										'value' => '',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Center' => 'Center',
								'Left Center' => 'Left Center',
								'Right Center' => 'Right Center',
								'Center Top' => 'Center Top',
								'Left Top' => 'Left Top',
								'Right Top' => 'Right Top',
								'Center Bottom' => 'Center Bottom',
								'Left Bottom' => 'Left Bottom',
								'Right Bottom' => 'Right Bottom',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_599f2f1a2618a',
							'label' => 'Caption',
							'name' => 'caption',
							'type' => 'text',
							'instructions' => '150 Character Limit',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_599f2f1a26188',
										'operator' => '!=',
										'value' => '',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => 150,
						),
						array(
							'key' => 'field_599f2f1a2618b',
							'label' => 'Link URL',
							'name' => 'link_url',
							'type' => 'url',
							'instructions' => 'Enter link to PDF, YouTube Video, or any site. Defaults to the image URL.',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_599f2f1a26188',
										'operator' => '!=',
										'value' => '',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
				),
				array(
					'key' => 'field_59a597e6a938a',
					'label' => 'Portrait Position',
					'name' => 'portrait_position',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae62b5',
								'operator' => '==',
								'value' => 'Portrait and Landscape',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Only Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae62b5',
								'operator' => '==',
								'value' => 'Portrait and Landscape',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Right of Landscape' => 'Right of Landscape',
						'Left of Landscape' => 'Left of Landscape',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_59e9491d15b91',
					'label' => 'Contact Info',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Contact Info',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_59e9493715b92',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => 'Example: "Contact Me!"',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Contact Info',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_59e9498d15b94',
					'label' => 'Email',
					'name' => 'email',
					'type' => 'text',
					'instructions' => 'Form submissions will also be sent here.',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Contact Info',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_59e949ad15b95',
					'label' => 'Phone',
					'name' => 'phone',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Contact Info',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_59e9495115b93',
					'label' => 'Location',
					'name' => 'location',
					'type' => 'google_map',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Contact Info',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'center_lat' => '',
					'center_lng' => '',
					'zoom' => '',
					'height' => '',
				),
				array(
					'key' => 'field_5a316c4958e83',
					'label' => 'Content Group',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Content Group Only',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Content Group',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5a316c7558e86',
					'label' => 'Grouped Content',
					'name' => 'grouped_content',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Content Group Only',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Content Group',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Site Content' => 'Site Content',
						'Users' => 'Users',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5a316c8758e87',
					'label' => 'Site Content',
					'name' => 'site_content',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Content Group Only',
							),
							array(
								'field' => 'field_5a316c7558e86',
								'operator' => '==',
								'value' => 'Site Content',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Content Group',
							),
							array(
								'field' => 'field_5a316c7558e86',
								'operator' => '==',
								'value' => 'Site Content',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
					),
					'taxonomy' => array(
					),
					'allow_null' => 0,
					'multiple' => 1,
					'return_format' => 'object',
					'ui' => 1,
				),
				array(
					'key' => 'field_5a316c9358e88',
					'label' => 'Users',
					'name' => 'users',
					'type' => 'user',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Content Group Only',
							),
							array(
								'field' => 'field_5a316c7558e86',
								'operator' => '==',
								'value' => 'Users',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Content Group',
							),
							array(
								'field' => 'field_5a316c7558e86',
								'operator' => '==',
								'value' => 'Users',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'role' => '',
					'allow_null' => 0,
					'multiple' => 1,
				),
				array(
					'key' => 'field_59a2f5fae6372',
					'label' => 'Segment Options',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => '',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Info Box',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Contact Info',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_59a2f5fae6385',
					'label' => 'Segment Display',
					'name' => 'segment_display',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae62b5',
								'operator' => '==',
								'value' => 'Single Media Item',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae62b5',
								'operator' => '==',
								'value' => 'Slideshow',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'One Column' => 'One Column',
						'Two Column' => 'Two Column',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_59a592d2ca146',
					'label' => 'Text Position',
					'name' => 'text_position',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae6385',
								'operator' => '==',
								'value' => 'Two Column',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Left of Media' => 'Left of Media',
						'Right of Media' => 'Right of Media',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_59a734cf1da38',
					'label' => 'Callout Size',
					'name' => 'callout_size',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Callout',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Small' => 'Small',
						'Medium' => 'Medium',
						'Large' => 'Large',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_59a2f5fae6397',
					'label' => 'Background',
					'name' => 'background',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => '',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Info Box',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Contact Info',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'White' => 'White',
						'Light Shade' => 'Light Shade',
						'Image' => 'Image',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_59a2f649a7b19',
					'label' => 'Background Image',
					'name' => 'background_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae6397',
								'operator' => '==',
								'value' => 'Image',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => '',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Info Box',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Contact Info',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_59a735011da39',
					'label' => 'Add background overlay?',
					'name' => 'add_background_overlay',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae6397',
								'operator' => '==',
								'value' => 'Image',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => '',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Callout',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Info Box',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_59a87692d8aac',
					'label' => 'Invert text color?',
					'name' => 'invert_text_color',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Media',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Callout',
							),
						),
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '==',
								'value' => 'Text and Content Group',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_59a2f5fae63aa',
					'label' => 'Add scroll icon?',
					'name' => 'add_scroll_icon',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => '',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Info Box',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Filterable Map',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_59a2f5fae63e6',
					'label' => 'Add button?',
					'name' => 'add_button',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => '',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Info Box',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Contact Info',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_59a2f5fae640f',
					'label' => 'Button Text',
					'name' => 'button_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae63e6',
								'operator' => '==',
								'value' => '1',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => '',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Info Box',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Contact Info',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_59a2f5fae6432',
					'label' => 'Button URL',
					'name' => 'button_url',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae63e6',
								'operator' => '==',
								'value' => '1',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => '',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Info Box',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Contact Info',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_59a970b9a2824',
					'label' => 'Open URL in new window?',
					'name' => 'open_url_in_new_window',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_59a2f5fae63e6',
								'operator' => '==',
								'value' => '1',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => '',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Info Box',
							),
							array(
								'field' => 'field_59a2f5fae61b3',
								'operator' => '!=',
								'value' => 'Contact Info',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5a302d0a36da4',
	'title' => 'Filterable Archive Feature',
	'fields' => array(
		array(
			'key' => 'field_5a302d0d8a3a6',
			'label' => 'Add Filterable Archive?',
			'name' => 'add_filterable_archive',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5a303147a2769',
			'label' => 'Content',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a302d0d8a3a6',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5a302ff1fb441',
			'label' => 'Archive Title',
			'name' => 'archive_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a302d0d8a3a6',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5a302d748a3a7',
			'label' => 'Archive Content',
			'name' => 'archive_content',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a302d0d8a3a6',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'post' => 'Posts',
				'user' => 'Users',
				'event' => 'Events',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5a302d908a3a8',
			'label' => 'User Roles',
			'name' => 'user_roles',
			'type' => 'checkbox',
			'instructions' => 'Select types of users to display.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a302d0d8a3a6',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5a302d748a3a7',
						'operator' => '==',
						'value' => 'user',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'administrator' => 'Administrators',
				'author' => 'Authors',
				'contributor' => 'Contributors',
				'editor' => 'Editors',
				'subscriber' => 'Subscribers',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'array',
		),
		array(
			'key' => 'field_5a302dcc8a3aa',
			'label' => 'Post Categories',
			'name' => 'post_categories',
			'type' => 'taxonomy',
			'instructions' => 'Select categories to pull posts from.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a302d0d8a3a6',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5a302d748a3a7',
						'operator' => '==',
						'value' => 'post',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'checkbox',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'object',
			'multiple' => 0,
		),
		array(
			'key' => 'field_5a316386380bf',
			'label' => 'Event Labels',
			'name' => 'event_labels',
			'type' => 'taxonomy',
			'instructions' => 'Select which type of events to show.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a302d0d8a3a6',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5a302d748a3a7',
						'operator' => '==',
						'value' => 'event',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'event_label',
			'field_type' => 'checkbox',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'object',
			'multiple' => 0,
		),
		array(
			'key' => 'field_5a303159a276a',
			'label' => 'Style Options',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a302d0d8a3a6',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5a303168a276b',
			'label' => 'Hide filters?',
			'name' => 'hide_filters',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a302d0d8a3a6',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5a3031a8a276c',
			'label' => 'Background',
			'name' => 'background',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a302d0d8a3a6',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'White' => 'White',
				'Light Shade' => 'Light Shade',
				'Image' => 'Image',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5a3031d3a276d',
			'label' => 'Background Image',
			'name' => 'background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a302d0d8a3a6',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5a3031a8a276c',
						'operator' => '==',
						'value' => 'Image',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
?>